version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ai_pipeline_db
    environment:
      POSTGRES_DB: pipeline_db
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: ai_pipeline_app
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: ["streamlit","run","app.py","--server.address=0.0.0.0"]

volumes:
  pgdata:

